### ISSUE TITLE
I don't understand how to use the plugin

### ISSUE THREAD

**Issue by Gakhramanzode** [jenkinsci/database-plugin#180]
### Describe your use-case which is not covered by existing documentation.

I went to **Dashboard->Manage Jenkins->Configure System**. Next, in the **Global Database** section, I entered the parameters for connecting to the Postgres database. I pressed **Test Connection** to make sure everything was in order. And what's next? How do I use this connection in my task? I [voiced](https://github.com/jenkinsci/database-postgresql-plugin/issues/87) this problem earlier, but in a different repository.
![image](https://user-images.githubusercontent.com/62985982/226549833-bb59f86c-f382-4fd8-84b9-0bfbfe77c929.png)
![image](https://user-images.githubusercontent.com/62985982/226549857-6375e917-7055-428a-a4e4-e0f79a043344.png)
![image](https://user-images.githubusercontent.com/62985982/226549872-3a1c6091-ead2-40be-b1f6-2a619de03a85.png)
![image](https://user-images.githubusercontent.com/62985982/226549890-c22167c1-9116-4194-a6aa-216abfd75a22.png)

**Comment by timja** [comment]
You don't say what you are trying to do.
Are you writing a plugin or something else?

This plugin is generally for plugins to consume.
There is a step you might be able to use but it's undocumented (at least in the README) and I haven't used it before

**Comment by Gakhramanzode** [comment]
Thank you for writing!

I want to create a job in which I will connect to Postgres and execute SQL queries.

As I pointed out earlier, I managed to successfully
configure and connect to my database in the Jenkins settings, but it is unclear how I can access it from the job.
![image](https://user-images.githubusercontent.com/62985982/226554133-2bd86076-f8be-44d5-b4f6-b48c7734d070.png)

**Comment by Gakhramanzode** [comment]
Can I give you a small example?

**Comment by timja** [comment]
You can give one.

I don't have one / I've never used this functionality.

**Comment by Gakhramanzode** [comment]
Ok, I get it. Thank you @timja. 
Have a nice day!
