### ISSUE TITLE
database plugin usage

### ISSUE THREAD

**Issue by es89247** [jenkinsci/database-plugin#63]
### Feature Request

HI, could you please upload a sample or example to use this plugin.
I am trying to connect a postgressql and execute a query from a freestyle jenkins jobs....thanks in advance

**Comment by timja** [comment]
This plugin isn't really for that

> This plugin is not meant to be used by end users by itself. It's supposed to be included through the dependencies of other plugins. If you are wondering how to store your job configuration etc. in a database, the answer is that you cannot.

it's for plugins to use.

That being said there is a couple of steps available:
https://github.com/jenkinsci/database-plugin/blob/master/src/main/java/org/jenkinsci/plugins/database/steps/SQLStep.java


https://github.com/jenkinsci/database-plugin/blob/master/src/main/java/org/jenkinsci/plugins/database/steps/DatabaseConnectionStep.java

Something like:

```
getDatabaseConnection(id: 'my-id') {
  sql id: 'my-id', sql: 'select * from blah'
}
```

untested and may not need to be wrapped in the getDatabaseConnection

If you or someone else figure it out it would be good to add to the docs.

There is also no test coverage on this, so no guarantees it still works.
